name: CI Pipeline Multi-Jobs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installer flake8
        run: pip install flake8
      - name: Executer lint
        run: |
          flake8 app/ tests/ --count --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    needs: lint 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installer les dépendances
        run: |
          pip install -e .
      - name: Executer pytest avec couverture
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installer l'outil de build
        run: pip install build
      - name: Générer le package Python (sdist et wheel)
        run: python -m build
      - name: Stocker le résultat (Artefact)
        uses: actions/upload-artifact@v3
        with:
          name: python-package-dist
          path: dist/