name: pipeline simple
on:
  push:
    branches: 
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: recuperer code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          Python-version: "3.11"
      - name: installer les dependencies 
        run: pip install -r requirements.txt
      - name: lint le code
        run: |
          flake8 app --count --select=E9,F63,F7,F82,F841 --show-source --statistics
          
      - name: lancer les tests
        run: pytest tests/ -v --cov=app